README.md
+ fixed readme badge bugs
+ fixed `Main.kt` location renaming bug
+ fixed integrated systems, as well
=> :bug: readme several bugs

.gitignore, README.md, src/main/kotlin/Main.kt
* Updating `.gitignore` to use with macOS
* Adding one line of code containing new feature to the [Main.kt](https://github.com/pool-party/pull-party-bot/blob/feature/hide-the-token/src/main/kotlin/Main.kt)
* Updating readme (a little fuck up with commit conventions)
=> Environment variable strategy to hide the token

.travis.yml, build.gradle, src/test/kotlin/MockTest.kt
+ Adding travis ci system
+ Adding codecov integration, as well. It has been tested locally with mock `src/test/kotlin/Test.kt`, so waiting for tests to appear.
=> :construction_worker: adding travis ci

Procfile
guys, sorry. need to change `worker` to `web` in heroku procfile
=> :recycle: heroku web

Procfile, build.gradle, src/main/kotlin/Main.kt
check heroku pipelines and create webhooks
=> :rocket: add webhooks

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Entities.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
Resolves #29, resolves #31, resolves #16
=> :sparkles: message party pulling

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :sparkles: default admins group

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :sparkles: add args validation

README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :ambulance: hotfixing directory renaming and linter warnings

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
=> :bug: api improvement

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :art: punctuation marks handling

CHANGELOG.md, README.md, build.gradle, src/main/kotlin/com/github/pool_party/pull_party_bot/Main.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Utils.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
=> Version 1.0.1

README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :bug: disabled tagging itself

build.gradle.kts, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Models.kt
=> :zap: database performance improving

README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
=> :sparkles: extending list command

README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
=> :bug: party name length assertion bugfix

.gitignore, README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/Configuration.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Utils.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
=> :sparkles: new party changing commands

build.gradle.kts, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Command.kt
=> :sparkles: party logging support

src/main/kotlin/com/github/pool_party/pull_party_bot/Configuration.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt, src/main/resources/defaults.properties
=> :sparkles: feedback command

.travis.yml, build.gradle.kts, src/main/kotlin/com/github/pool_party/pull_party_bot/Configuration.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ChangePartyCommands.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/InformationCommands.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommands.kt
=> :sparkles: jaro winkler algorithm integration

README.md, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/EveryMessageInteraction.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Handlers.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/MigrationHandler.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommands.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Models.kt, src/main/kotlin/com/github/pool_party/pull_party_bot/database/dao/ChatDao.kt, src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/DeleteCommandTest.kt, src/test/kotlin/com/github/pool_party/pull_party_bot/database/dao/ChatInMemoryDao.kt
=> :bug: fixing supergroup migration bug

src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommands.kt
=> :bug: making party pulling suggestions unique

README.md, build.gradle.kts, src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt, src/main/resources/db/migration/V0__Base.sql, src/main/resources/db/migration/V1__Add_cascade.sql, src/main/resources/db/migration/V2__Aliases.sql, src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/testcontainers/AbstractTestContainerTest.kt
=> :card_file_box: database migrations

CHANGELOG.md, Procfile, build.gradle.kts
- :sparkles: Bugfix and chat error logging
- :arrow_up: version bump
=> :arrow_up: version bump
